name: Pull Request Merged

# on:
#   pull_request:
#     types:
#       - closed
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add comment
      run: |
        if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
          Congratulations :)
          pull_request_number=${{ github.event.pull_request.number }}
          comment_body=":tada: Congratulations! The pull request #${pull_request_number} has been merged successfully! :tada:"
          echo "${comment_body}" | gh pr review --approve --comment --body -
        fi
